steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: 
    - 'functions'
    - 'deploy'
    - 'mondo-notifier-dev'
    - '--region=us-east1'
    - '--service-account=clingen-mondo-notify@clingen-dx.iam.gserviceaccount.com'
    - '--set-env-vars=???'
    - '--allow-unauthenticated'
    - '--trigger-http'
    - '--memory=512MB'
    - '--runtime=python39'
    - '--entry-point=mondo_notifier'
