steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'mondo-notifier', '--region=us-east1', '--service-account=clingen-mondo-notify@clingen-dx.iam.gserviceaccount.com', '--allow-unauthenticated', '--trigger-http', '--memory=128MB', '--runtime', 'python39', '--entry-point', 'mondo_notifier']
